//
// Created by ale on 16/05/23.
//

#ifndef PALANOCHATUTENTI_MILLISECONDTIME_H
#define PALANOCHATUTENTI_MILLISECONDTIME_H

#include <string>

long getCurrentUTC();

#endif //PALANOCHATUTENTI_MILLISECONDTIME_H
